# 自定义命令权限定义

[[permission]]
identifier = "allow-on-login-success"
description = "允许调用 on_login_success"
commands.allow = ["on_login_success"]

[[permission]]
identifier = "allow-on-logout"
description = "允许调用 on_logout"
commands.allow = ["on_logout"]

[[permission]]
identifier = "allow-add-shop-channel"
description = "允许调用 add_shop_channel"
commands.allow = ["add_shop_channel"]

[[permission]]
identifier = "allow-start-backend-channel"
description = "允许调用 start_backend_channel"
commands.allow = ["start_backend_channel"]

[[permission]]
identifier = "allow-shop-account"
description = "允许调用 shop_account"
commands.allow = ["shop_account"]

[[permission]]
identifier = "allow-add-shop"
description = "允许调用 add_shop"
commands.allow = ["add_shop"]

[[permission]]
identifier = "allow-delete-shop"
description = "允许调用 delete_shop"
commands.allow = ["delete_shop"]

[[permission]]
identifier = "allow-shop-list"
description = "允许调用 shop_list"
commands.allow = ["shop_list"]

[[permission]]
identifier = "allow-select-shop"
description = "允许调用 select_shop"
commands.allow = ["select_shop"]

[[permission]]
identifier = "allow-select-platform"
description = "允许调用 select_platform"
commands.allow = ["select_platform"]

[[permission]]
identifier = "allow-greet"
description = "允许调用 greet"
commands.allow = ["greet"]

[[permission]]
identifier = "allow-on-request"
description = "允许调用 on_request"
commands.allow = ["on_request"]

[[permission]]
identifier = "allow-on-ws"
description = "允许调用 on_ws"
commands.allow = ["on_ws"]

[[permission]]
identifier = "allow-on-ws-binary"
description = "允许调用 on_ws_binary"
commands.allow = ["on_ws_binary"]

[[permission]]
identifier = "allow-dy-ws-recv"
description = "允许调用 dy_ws_recv"
commands.allow = ["dy_ws_recv"]

[[permission]]
identifier = "allow-dy-ws-send"
description = "允许调用 dy_ws_send"
commands.allow = ["dy_ws_send"]

[[permission]]
identifier = "allow-on-http-response-intercepted"
description = "允许调用 on_http_response_intercepted"
commands.allow = ["on_http_response_intercepted"]

[[permission]]
identifier = "allow-shop-name-callback"
description = "允许调用 shop_name_callback"
commands.allow = ["shop_name_callback"]

[[permission]]
identifier = "allow-on-get-link-info"
description = "允许调用 on_get_link_info"
commands.allow = ["on_get_link_info"]

[[permission]]
identifier = "allow-pdd-ws-recv"
description = "允许调用 pdd_ws_recv"
commands.allow = ["pdd_ws_recv"]

[[permission]]
identifier = "allow-pdd-ws-send"
description = "允许调用 pdd_ws_send"
commands.allow = ["pdd_ws_send"]

[[permission]]
identifier = "allow-pdd-send-message"
description = "允许调用 pdd_send_message"
commands.allow = ["pdd_send_message"]

[[permission]]
identifier = "allow-pdd-crypto-callback"
description = "允许 JS webview 回调加密参数"
commands.allow = ["pdd_crypto_callback"]

